apiVersion: apps/v1
kind: Deployment
metadata:
   name: homework
   namespace: testing3
spec:
   replicas: 3
   selector:
      matchLabels:
         app: homework
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: homework
      spec:
         containers:
         - name: homework
           image: xapepama/nginx:homework_v1.5
           readinessProbe:
             httpGet:
               path: /health
               port: 80
           ports:
             - containerPort: 80