apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homework2-servicemonitor
  namespace: monitoring
  labels:
    app: homework2-py-app
    release: prom
spec:
  jobLabel: homework2-py-app
  endpoints:
  - interval: 15s
    path: /metrics
  selector:
    matchLabels:
      app: homework2-py-app
  namespaceSelector:
    matchNames:
    - default
