prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

grafana:
  adminPassword: adminadmin
  enabled: true
  namespaceOverride: ""

  ## Deploy default dashboards.
  ##
  defaultDashboardsEnabled: true

  adminPassword: prom-operator

  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
    hosts: 
      - grafana.arch.homework
    path: /
  
prometheus:
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
    hosts: 
      - prometheus.arch.homework
    path: /
    pathType: Prefix