{
 "title": "My dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(app_request_count_total[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency by endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n      sum by (le, endpoint) \r\n         (rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000\r",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Status 200 Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"2.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Status 500 Ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "POD MEMORY REQUEST",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", image!=\"\", container_name!=\"POD\"}) by (pod, container_name, namespace, slave)\r\n "
    }
   ]
  },
  {
   "title": "POD CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(100 * sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container_name!=\"POD\"}[5m])) by (pod, container_name, namespace, slave))"
    }
   ]
  },
  {
   "title": "Status 500 app",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_count_total{http_status=~\"5.+\"}[1m])"
    }
   ]
  }
 ]
}