apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: echoserver.default.svc.cluster.local

spec:
  rules:
  - host: echoserver.arch.homework
    http:
      paths:
        - path: /
          backend:
            serviceName: echoserver
            servicePort: 80
