apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-servicemonitor
  namespace: monitoring
  labels:
    app: ingress-nginx
    release: prom
spec:
  jobLabel: ingress-nginx
  endpoints:
  - interval: 15s
    path: /metrics
  selector:
    matchLabels:
      app: ingress-nginx
  namespaceSelector:
    matchNames:
    - ingress-nginx
