apiVersion: v1
kind: Service
metadata:
  name: homework2-service
  labels:
    app: homework2-py-app
spec:
  selector:
    app: homework2-py-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
      nodePort: 30001  
  type: NodePort
