apiVersion: apps/v1
kind: Deployment
metadata:
    name: homework2-deployment
    namespace: testing3
spec:
    replicas: 2
    selector:
       matchLabels:
          app: homework2-py-app
    template:
       metadata:
          labels:
             app: homework2-py-app
       spec:
          containers:
          - name: homework2-py
            image: homework2-py:v1
            env:
              - name: DATABASE_URI
                valueFrom:
                  secretKeyRef:
                    name: homework2-secret
                    key: DATABASE_URI
              - name: GREETING
                valueFrom:
                  configMapKeyRef:
                    name: homework2-config
                    key: GREETING
            ports:
              - name: web
                containerPort: 80
          initContainers:
          - name: init-mydb
            env:
              - name: DATABASE_URI
                valueFrom:
                  secretKeyRef:
                    name: homework2-secret
                    key: DATABASE_INIT_URI
            image: postgres:latest
            command:
              - sh
              - "-c"
              - |
                psql $DATABASE_URI <<'EOF'
                  CREATE TABLE clients(id SERIAL PRIMARY KEY, name VARCHAR NOT NULL);
                EOF
