fullnameOverride: postgres
postgresqlUsername: myuser
postgresqlPassword: passwd
postgresqlDatabase: myapp

service:
  type: NodePort
  port: 5432
  nodePort: 30000

persistence:
  enabled: true
  size: 1Gi
