fullnameOverride: postgres
postgresqlUsername: myuser
postgresqlPassword: passwd
postgresqlDatabase: myapp

postgresqlMaxConnections: 1000
postgresqlPostgresConnectionLimit: 1000
postgresqlDbUserConnectionLimit: 1000

service:
  port: 5432

persistence:
  enabled: false
  size: 1Gi

## Configure metrics exporter
##
metrics:
  enabled: true
  # resources: {}
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9187'
    loadBalancerIP:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prom
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s
